baseurl = "http://decay42.github.io/billard-homepage/"
languageCode = "de-de"
title = "1. Magdeburger Poolbillardverein"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "1. Magdeburger PBV"
	description = "Homepage des 1. Magdeburger Poolbillardvereins"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "1. Magdeburger Poolbillardverein"

		[params.navigation.links]
			#about     = "Über uns"
			#services  = "Services"
			#portfolio = "Portfolio"
			contact   = "Kontakt"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Herzlich Willkommen"
		subtitle   = "Hier entsteht die Website des 1. Magdeburger Poolbillardvereins."
		buttonText = "Erfahre wie du uns erreichst"


	# Contact section
	[params.contact]
		headline = "So erreichst du uns!"
		description = "Du möchtest mal reinschnuppern? Dann komm doch zu unseren Trainingszeiten vorbei!"
		contact_url = "http://www.billardhouse-md.de/"
		address0 = "Billardhouse Magdeburg"
		address1 = "Liebknechtstraße 87"
		address2 = "39110 Magdeburg"
		times = "Montag und Mittwoch, ab 18 Uhr"
		email = "feedback@startbootstrap.com"